[tool.poetry]
name = "segmentation"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
torch = "^2.1.2"
numpy = "^1.26.3"
matplotlib = "^3.8.2"
seaborn = "^0.13.1"
kaggle = "^1.6.3"
torchvision = "^0.16.2"
pytorch-lightning = "^2.1.3"
lightning = "^2.1.3"
tensorboard = "^2.15.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
